#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HtmlParserProject.Resource", IsApplication=true)]

namespace HtmlParserProject
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040019
			public const int alternate_row = 2130968601;
			
			// aapt resource value: 0x7f04001f
			public const int black = 2130968607;
			
			// aapt resource value: 0x7f04001a
			public const int color_profit = 2130968602;
			
			// aapt resource value: 0x7f040000
			public const int contents_text = 2130968576;
			
			// aapt resource value: 0x7f040020
			public const int dark_green = 2130968608;
			
			// aapt resource value: 0x7f040001
			public const int encode_view = 2130968577;
			
			// aapt resource value: 0x7f04001b
			public const int fba_price = 2130968603;
			
			// aapt resource value: 0x7f040021
			public const int grey = 2130968609;
			
			// aapt resource value: 0x7f040002
			public const int help_button_view = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int help_view = 2130968579;
			
			// aapt resource value: 0x7f04001d
			public const int new_price = 2130968605;
			
			// aapt resource value: 0x7f040004
			public const int possible_result_points = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int result_image_border = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int result_minor_text = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int result_points = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int result_text = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int result_view = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int sbc_header_text = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int sbc_header_view = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int sbc_layout_view = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int sbc_list_item = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int sbc_page_number_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int sbc_snippet_text = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int share_text = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int status_text = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int status_view = 2130968593;
			
			// aapt resource value: 0x7f040017
			public const int title_book_found = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int title_book_not_found = 2130968600;
			
			// aapt resource value: 0x7f040013
			public const int transparent = 2130968595;
			
			// aapt resource value: 0x7f04001c
			public const int used_price = 2130968604;
			
			// aapt resource value: 0x7f040014
			public const int viewfinder_frame = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int viewfinder_laser = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int viewfinder_mask = 2130968598;
			
			// aapt resource value: 0x7f04001e
			public const int white = 2130968606;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050004
			public const int buttons_width_tablet = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int checkbox_padding_tablet = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int margin_between_table_items = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int margin_left_phone = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int margin_left_tablet = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int margin_right_phone = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int margin_right_tablet = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int numpad_button_height = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int numpad_button_width = 2131034120;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int diagramSmall = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int mainLayout = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int progress = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int table1 = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int table2 = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int tvTable1 = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int tvTable2 = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int camel = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int button_ok = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int no_connection_message = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int no_connection_title = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Margins = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
